FROM python:3.11-slim-trixie

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/start.sh .
COPY backend/dev-start.sh .

RUN chmod +x /app/start.sh
RUN chmod +x /app/dev-start.sh

EXPOSE 8000

ENTRYPOINT ["./dev-start.sh"]