from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd2a227ace4'
down_revision: Union[str, Sequence[str], None] = '6518b024dcbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['activities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index('ix_buildings_lat_lon', 'buildings', ['latitude', 'longitude'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_organization_name_lower', 'organizations', [sa.literal_column('lower(name)')], unique=False)
    op.create_index(op.f('ix_organizations_building_id'), 'organizations', ['building_id'], unique=False)
    op.create_table('organization_activities',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'activity_id')
    )
    op.create_index('ix_org_act_activity_id', 'organization_activities', ['activity_id'], unique=False)
    op.create_table('organization_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_organization_phones_organization_id'), 'organization_phones', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_phones_organization_id'), table_name='organization_phones')
    op.drop_table('organization_phones')
    op.drop_index('ix_org_act_activity_id', table_name='organization_activities')
    op.drop_table('organization_activities')
    op.drop_index(op.f('ix_organizations_building_id'), table_name='organizations')
    op.drop_index('ix_organization_name_lower', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_buildings_lat_lon', table_name='buildings')
    op.drop_table('buildings')
    op.drop_table('activities')
    # ### end Alembic commands ###
